/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * Kelompok 11
 * Gerald Ergi Bhaskara Natajaya (1301180133)
 * Jose Vernando (1301180205)
 * Muhammad Haidir Ali (1301180392)
 */
package aplikasiparkir;

import java.awt.Font;
import java.awt.print.PrinterException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ACER
 */
public class AplikasiParkir extends javax.swing.JFrame {

    double waktu, total, jenis, harga, bayar, a, b;
    String total_bayar;
    
    public void selectData(){
        String kolom[] = {"No Polisi", "Jenis Kendaraan", "Lama Parkir", "Total Bayar"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM parkir";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String no_polisi = rs.getString(2);
                String jenis = "";
                if ("mobil".equals(rs.getString(3))){
                    jenis = "Mobil";
                }else{
                    jenis = "Motor";
                }
                String waktu = rs.getString(4);
                String total = rs.getString(5);
                String data[] = {no_polisi,jenis,waktu,total};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(AplikasiParkir.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
        JTableHeader header = tblData.getTableHeader();
        header.setFont(new Font("Dialog", Font.BOLD, 14));
    }
    
    public AplikasiParkir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGKendaraan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtBiayaParkir = new javax.swing.JTextField();
        TxtNoPolisi = new javax.swing.JTextField();
        RBMobil = new javax.swing.JRadioButton();
        BGKendaraan.add(RBMobil);
        RBMotor = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        TxtLamaParkir = new javax.swing.JTextField();
        TxtJamKeluar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtJamMasuk = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtnProcess = new javax.swing.JButton();
        BtnClear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TxtTotalBiayaParkir = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No Polisi");

        jLabel2.setText("Jenis Kendaraan");

        jLabel3.setText("Biaya Parkir");

        jLabel4.setText("Jam Masuk:");

        TxtBiayaParkir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBiayaParkirActionPerformed(evt);
            }
        });

        TxtNoPolisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoPolisiActionPerformed(evt);
            }
        });

        RBMobil.setText("Mobil");
        RBMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMobilActionPerformed(evt);
            }
        });

        RBMotor.setText("Motor");
        RBMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMotorActionPerformed(evt);
            }
        });

        jLabel5.setText("Jam Keluar:");

        TxtJamKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtJamKeluarActionPerformed(evt);
            }
        });

        jLabel6.setText("Lama Parkir");

        jLabel7.setText("jam");

        BtnProcess.setText("Process");
        BtnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProcessActionPerformed(evt);
            }
        });

        BtnClear.setText("Clear");
        BtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClearActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Biaya Parkir");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Polisi", "Jenis Kendaraan", "Lama Parkir", "Total Bayar"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btCetak.setText("Cetak");
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtLamaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RBMobil)
                                                .addGap(39, 39, 39)
                                                .addComponent(RBMotor))))
                                    .addComponent(TxtNoPolisi)
                                    .addComponent(TxtBiayaParkir)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnProcess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTotalBiayaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnSimpan))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TxtNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBMobil)
                    .addComponent(jLabel2)
                    .addComponent(RBMotor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtBiayaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(TxtJamKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtJamMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtLamaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnProcess)
                    .addComponent(BtnClear))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TxtTotalBiayaParkir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btCetak))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBiayaParkirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBiayaParkirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBiayaParkirActionPerformed

    private void TxtNoPolisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoPolisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNoPolisiActionPerformed

    private void RBMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMobilActionPerformed
        // TODO add your handling code here:
        TxtBiayaParkir.setText("5000");
    }//GEN-LAST:event_RBMobilActionPerformed

    private void RBMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMotorActionPerformed
        // TODO add your handling code here:
        TxtBiayaParkir.setText("2000");
    }//GEN-LAST:event_RBMotorActionPerformed

    private void TxtJamKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtJamKeluarActionPerformed
        // TODO add your handling code here:
        double JamMasuk, JamKeluar, LamaParkir;
        JamMasuk = Double.parseDouble(TxtJamMasuk.getText());
        JamKeluar = Double.parseDouble(TxtJamKeluar.getText());
        LamaParkir = JamKeluar - JamMasuk;
        
        String.valueOf(LamaParkir);
        TxtLamaParkir.setText(""+LamaParkir);
    }//GEN-LAST:event_TxtJamKeluarActionPerformed

    private void BtnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProcessActionPerformed
        // TODO add your handling code here:
       double JamMasuk,JamKeluar,LamaParkir;
        JamMasuk=Double.parseDouble(TxtJamMasuk.getText());
        JamKeluar=Double.parseDouble(TxtJamKeluar.getText());
        LamaParkir=JamKeluar-JamMasuk;
       
        String.valueOf(LamaParkir);
        TxtLamaParkir.setText(""+LamaParkir);
        
        double Total,Jam,Hasil;
        Total=Double.parseDouble(TxtBiayaParkir.getText());
        Jam=Double.parseDouble(TxtLamaParkir.getText());
        Hasil=Total*Jam;
       
        String.valueOf(Hasil);
        TxtTotalBiayaParkir.setText(""+Hasil);
    }//GEN-LAST:event_BtnProcessActionPerformed

    private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClearActionPerformed
        // TODO add your handling code here:
        TxtNoPolisi.setText("");
        TxtBiayaParkir.setText("");
        BGKendaraan.clearSelection();
        TxtJamMasuk.setText("");
        TxtJamKeluar.setText("");
        TxtLamaParkir.setText("");
        TxtTotalBiayaParkir.setText("");
    }//GEN-LAST:event_BtnClearActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new Halaman_Login().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if ("".equals(TxtNoPolisi.getText()) || "".equals(TxtLamaParkir.getText())){
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
    }
        else {
            String jenis = "";
            if (RBMobil.isSelected()){
                jenis = "Mobil";
            }else {
                jenis = "Motor";
            }
            
            String SQL = "INSERT INTO parkir (no_polisi,jenis,waktu,total)"
            + "VALUES('"+TxtNoPolisi.getText()+"','"+jenis+"',"
            + "'"+TxtLamaParkir.getText()+"','"+TxtTotalBiayaParkir.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else {
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
        MessageFormat judul = new MessageFormat("Data Parkir");
        MessageFormat footer = new MessageFormat("page(0,number,integer");
        
        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, judul, footer);
        }catch (PrinterException ex){
            System.err.print("Error Printer");
        }
    }//GEN-LAST:event_btCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiParkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiParkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGKendaraan;
    private javax.swing.JButton BtnClear;
    private javax.swing.JButton BtnProcess;
    private javax.swing.JRadioButton RBMobil;
    private javax.swing.JRadioButton RBMotor;
    private javax.swing.JTextField TxtBiayaParkir;
    private javax.swing.JTextField TxtJamKeluar;
    private javax.swing.JTextField TxtJamMasuk;
    private javax.swing.JTextField TxtLamaParkir;
    private javax.swing.JTextField TxtNoPolisi;
    private javax.swing.JTextField TxtTotalBiayaParkir;
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
